### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by isabelle-dr**
test for issue [#212](https://github.com/MobilityData/mobility-database-catalogs/pull/212)

### CODE REVIEW

**Review by emmambd — APPROVED** [review]

**Comment by isabelle-dr** [comment]
Love it -
It would be amazing to do it for the 10th PR mark, the 50, the 100!

**Comment by isabelle-dr** [comment]
And these thresholds could unlock new role possibilities in the project
🤔
Some contributors asked me "how can we join the technical committee" and I currently don't have a great answer.

**Comment by emmambd** [comment]
Yes, that would be super fun! Maybe the role thresholds could be based on a mix of the number of PRs merged + the tag of the issue.

**Comment by maximearmstrong** [comment]
Wow, I love that gif!

> Maybe the role thresholds could be based on a mix of the number of PRs merged + the tag of the issue.

That would be the best! Some PRs could count for much more: changes representing +5% of the code base, new features, major refactoring, etc.

**Pull request merged**
